openapi: 3.1.0
info:
  title: Solar Control - Arduino service
  description: |-
   This service is designed to collect and process the parameters of the DC and AC circuits of the solar power plant, and then send the data to the client
  version: 1.0.0
servers:
  - url: '{protocol}://esp8266.local'
    variables:
      protocol:
        enum:
          - http
        default: http
tags:
  - name: ESP
    description: Operations with ESP board
  - name: Sensor
    description: Access to connected sensors
  - name: PZEM
    description: Access to PZEM sensors
  - name: Relay
    description: Access to relays
paths:
  /health:
    get:
      tags:
        - ESP
      summary: Returns ESP health status
      operationId: getEspHealth
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                examples:
                  - UP
  /status:
    get:
      tags:
        - ESP
      summary: Returns a status of components connected to the ESP
      operationId: getEspStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EspStatus'
  /sensors:
    get:
      tags:
        - Sensor
      summary: Returns values of all connected sensors
      operationId: getSensorsValues
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorsData'
  /pzems/address:
    patch:
      tags:
        - PZEM
      summary: Sets the address to PZEM
      operationId: setPzemAddress
      parameters:
        - name: name
          in: query
          description: The name of the PZEM for which the address is changed
          required: true
          schema:
            type: string
        - name: address
          in: query
          description: The address to set in PZEM memory
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 248
            default: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PzemAddress'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                examples:
                  - The "address" param should be in the range between 1 and 247
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
                examples:
                  - PZEM with entered name is not found
  /pzems/counter:
    delete:
      tags:
        - PZEM
      summary: Resets the energy counter of all PZEMs
      operationId: resetEnergyCounter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PzemCounter'
  /relays:
    get:
      tags:
        - Relay
      summary: Returns a status of connected relay
      operationId: getRelayStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelayStatus'
  /relays/on:
    post:
      tags:
        - Relay
      summary: Turns relay ON and returns status
      operationId: turnRelayOn
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelayStatus'
  /relays/off:
    post:
      tags:
        - Relay
      summary: Turns relay OFF and returns status
      operationId: turnRelayOff
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelayStatus'
  /relays/toggle:
    post:
      tags:
        - Relay
      summary: Inverts relay state and returns status
      operationId: toggleRelay
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelayStatus'

components:
  schemas:
    EspStatus:
      type: object
      properties:
        wifi:
          $ref: '#/components/schemas/WiFiStatus'
        date:
          $ref: '#/components/schemas/DateStatus'
        pzems:
          type: array
          items:
            $ref: '#/components/schemas/PzemStatus'
        eeprom:
          $ref: '#/components/schemas/EepromStatus'
      required:
        - wifi
        - date
        - pzems
        - eeprom
    WiFiStatus:
      type: object
      properties:
        ip:
          type: string
          description: Station interface IP address
          format: ipv4
          examples:
            - "198.51.100.42"
        mac:
          type: string
          description: Station interface MAC address
          pattern: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'
          examples:
            - "54:8F:94:AE:2B:8A"
      required:
        - ip
        - mac
    DateStatus:
      type: object
      properties:
        createdAtGmt:
          type: string
          description: UTC Date in ISO format
          format: date-time
          examples:
            - "2024-09-01T05:30:35.637Z"
        createdAt:
          type: string
          description: Date in the local timezone
          format: date-time
          examples:
            - "2024-09-01T08:30:35.637Z"
      required:
        - createdAtGmt
        - createdAt
    PzemStatus:
      type: object
      properties:
        name:
          type: string
          description: The name of the PZEM sensor
          examples:
            - acInput
        isConnected:
          type: boolean
          description: true/false indicator when the PZEM is connected
        currentAddress:
          type: integer
          format: int32
          description: Configured address to connect to the PZEM
          minimum: 1
          maximum: 248
          examples:
            - 2
        savedAddress:
          type: integer
          format: int32
          description: Address saved in PZEM memory
          minimum: 0
          maximum: 248
          examples:
            - 2
        savedShuntType:
          type: integer
          format: int32
          description: Shunt type saved in PZEM memory
          minimum: 0
          maximum: 3
          examples:
            - 1
      required:
        - name
        - isConnected
        - currentAddress
        - savedAddress
    EepromStatus:
      type: object
      properties:
        isConnected:
          type: boolean
          description: true/false indicator when the EEPROM module is connected
      required:
        - isConnected
    SensorsData:
      type: object
      properties:
        createdAtGmt:
          type: string
          format: date-time
          description: Data collection date in UTC
          examples:
            - "2024-09-01T12:22:05.042Z"
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/Sensor'
      required:
        - createdAtGmt
        - pzems
    Sensor:
      type: object
      properties:
        name:
          type: string
          description: The name of the sensor
          examples:
            - acInput
        voltageV:
          type: number
          format: float
          description: AC/DC voltage in Volts
          examples:
            - 233.1000061
        currentA:
          type: number
          format: float
          description: AC/DC current in Amps
          examples:
            - 0.097999997
        powerKw:
          type: number
          format: float
          description: AC/DC active power in kW
          examples:
            - 0.0135
        energyKwh:
          type: number
          format: float
          description: AC/DC active energy in kWh since last reset
          examples:
            - 0.003
        frequencyHz:
          type: number
          format: float
          description: AC frequency in Hz
          examples:
            - 50
        powerFactor:
          type: number
          format: float
          description: AC power factor of the load
          examples:
            - 0.589999974
        t1EnergyKwh:
          type: number
          format: float
          description: Calculated value of active energy during T1 zone
          examples:
            - 0.004999999
        t2EnergyKwh:
          type: number
          format: float
          description: Calculated value of active energy during T2 zone
          examples:
            - 0.012914399
      required:
        - name
        - voltageV
    PzemAddress:
      type: object
      properties:
        name:
          type: string
          description: The name of the PZEM sensor
          examples:
            - acInput
        addressToSet:
          type: integer
          format: int32
          description: Address to save in PZEM memory
          minimum: 1
          maximum: 248
          examples:
            - 1
        isChanged:
          type: boolean
          description: true/false indicator when the address is set
      required:
        - name
        - addressToSet
        - isChanged
    PzemCounter:
      type: object
      properties:
        name:
          type: string
          description: The name of the PZEM sensor
          examples:
            - acInput
        isReset:
          type: boolean
          description: true/false indicators for every PZEM to notify which counters were reset
      required:
        - name
        - isReset
    RelayStatus:
      type: object
      properties:
        status:
          type: boolean
          description: Current status of the relay
          examples:
            - true
      required:
        - status
